### ISSUE TITLE
Feature Request: Drawing Primitives

### ISSUE THREAD

**Issue by anthonyfinch** [zacharycarter/dEngine#31]
FRAG should support drawing primitives. Use cases are:

- for simple game prototypes (or just games with a very simple visual style)
- for debug and "editor" gui systems - eg. drawing bounding boxes, "handles" to resize, move objects etc.

As a list of possible primitive to start with, I would suggest something like that supported by sdl2, ie:

- lines
- points
- rects
with filled and non-filled variants.

See the discussion on the forum here: http://community.fragworks.io/t/possible-feature-request-drawing-primitives/19 ( @zacharycarter has some implementation suggestions here. )

**Comment by zacharycarter** [comment]
This is going to require porting :
https://github.com/bkaradzic/bgfx/tree/master/examples/common/nanovg
and more specifically :
https://github.com/bkaradzic/bgfx/blob/master/examples/common/nanovg/nanovg_bgfx.cpp

**Comment by zacharycarter** [comment]
Implemented with 0b46c89c1f9042c44934bd11d8839f1ee4fd4be8
