### ISSUE TITLE
could not load: bgfx-shared-lib(Debug|Release).dll

### ISSUE THREAD

**Issue by kingofoz** [zacharycarter/dEngine#38]
Hi @zacharycarter 
I have installed Frag and built some examples, but seems one dll is necessary to run examples: bgfx-shared-lib(Debug|Release).dll.
Can you please tell me how to find or generate it?

Thanks!

**Comment by kingofoz** [comment]
I compiled a bgfx dll and downloaded a openal32.dll, and 05 example can be run, but it stops to work. Please see the output:
D:\labs\frag\examples\desktop\05-gui>main
Initializing Frag - v0.0.1...
Initializing logging subsystem...
DEBUG Logging subsystem initialized.
DEBUG Initializing events subsystem...
DEBUG Events subsystem initialized.
DEBUG Initializing input subsystem...
DEBUG Input subsystem initialized.
DEBUG Initializing graphics subsystem...
DEBUG Graphics subsystem initialized.
DEBUG Initializing asset management subsystem...
DEBUG Asset management subsystem initialized.
DEBUG Initializing IMGUI subsystem...

I am afraid I still have some dlls to install?

**Comment by zacharycarter** [comment]
Hi @kingofoz!

Example 5 shouldn't require any other DLLs the other examples don't. It does require Nuklear - did you run ```nimble install``` in the root directory of FRAG?

Do any other examples run?

What operating system are you on?

**Comment by kingofoz** [comment]
Hi @zacharycarter 
I tried examples 0 to 6, no one can run on my Windows 7 x64 box. And it does need a bgfx dll and a openal32.dll because it hinted for them.
Yes, I ran 'nimble install -y' in the root directory of Frag. I installed Frag from source.
Maybe I need some dependencies? How to install Nuklear?

**Comment by zacharycarter** [comment]
Going to go ahead and close this since the problem has been taken to gitter.
